{{- if and .Values.fluentbitOperator.enabled .Values.fluentbitOperator.cleanupCustomResource }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fluentbit-operator.fullname" . }}-operator-cleanup
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "fluentbit-operator.name" . }}-operator
{{ include "fluentbit-operator.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "fluentbit-operator.fullname" . }}-operator-cleanup
      labels:
        app: {{ template "fluentbit-operator.name" . }}-operator
{{ include "fluentbit-operator.labels" . | indent 8 }}
    spec:
    {{- if .Values.global.rbac.create }}
      serviceAccountName: {{ template "fluentbit-operator.operator.serviceAccountName" . }}
    {{- end }}
      containers:
        - name: kubectl
          image: "{{ .Values.image.hyperkube.repository }}:{{ .Values.image.hyperkube.tag }}"
          imagePullPolicy: "{{ .Values.image.hyperkube.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - >
              kubectl delete filter --all;
              kubectl delete input --all;
              kubectl delete output --all;
              kubectl delete fluentbitconfig --all;
              kubectl delete fluentbit --all;
              sleep 10;

              kubectl delete crd filters.logging.kubesphere.io;
              kubectl delete crd fluentbitconfigs.logging.kubesphere.io;
              kubectl delete crd fluentbits.logging.kubesphere.io;
              kubectl delete crd inputs.logging.kubesphere.io;
              kubectl delete crd outputs.logging.kubesphere.io;
      restartPolicy: OnFailure
{{- end }}