{{- if and .Values.fluentbit.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "fluentbit-operator.fullname" . }}-fluentbit-psp
  labels:
    app: {{ template "fluentbit-operator.name" . }}-fluentbit
{{ include "fluentbit-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fluentbit-operator.fullname" . }}-fluentbit-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "fluentbit-operator.fluentbit.serviceAccountName" . }}
    namespace: {{ $.Release.Namespace }}
{{- end }}

