
{{- if and .Values.fluentbit.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fluentbit-operator.fullname" . }}-fluentbit-psp
  labels:
    app: {{ template "fluentbit-operator.name" . }}-fluentbit
{{ include "fluentbit-operator.labels" . | indent 4 }}
rules:
{{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if semverCompare "> 1.15.0-0" $kubeTargetVersion }}
- apiGroups: ['policy']
{{- else }}
- apiGroups: ['extensions']
{{- end }}
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "fluentbit-operator.fullname" . }}-fluentbit
{{- end }}
